### ISSUE TITLE
Refile dependency issue

### ISSUE THREAD

**Issue by mulaiko** [krists/refile-postgres#13]
HI there,

Running into this error:

Bundler could not find compatible versions for gem "refile":
  In Gemfile:
    refile

    refile-postgres was resolved to 1.4.0, which depends on
      refile (~> 0.6.2)

Could not find gem 'refile (~> 0.6.2)', which is required by gem 'refile-postgres', in any of the relevant sources:
  https://github.com/refile/refile.git (at master@e690bf5)

How can I resolve this issue?

**Comment by krists** [comment]
Hi, @mulaiko!

Refile master has version 0.7.0 but it hasn't been officially released yet. 
I have made few updated that should allow to use refile's master branch for a while.

Please check refile-postgres version 1.4.1
