### ISSUE TITLE
Assets precompile issue with initializer

### ISSUE THREAD

**Issue by dspaeth-faber** [krists/refile-postgres#4]
Hi (again ;)),

I did discover an issue with 'assets:precompile' (Rails 4).
Normaly Rails 4 does not need a db connection for assets:precompile.
But with refile-postgres setup within the initializer a connection is needed.

This is bad in my case because I don't have a route from my asset hosts to my db servers.

Proc initializer become more and more charming ;)

regards 
dieter

**Comment by krists** [comment]
Yes. DB connection should not be used in compilation. The whole initialization process should be reworked to take this and #2 into account. @dspaeth-faber Is this something you would like to try?

**Comment by krists** [comment]
Should be fixed in 1e6c7968ac49b9763b1be51d2a281e8a3c571269
