### ISSUE TITLE
pg-largeobject access error

### ISSUE THREAD

**Issue by moubry** [krists/refile-postgres#6]
I'm having this issue on Heroku: http://stackoverflow.com/questions/15014692/pg-largeobject-access-on-heroku

Inserting file attachements into Postgres appears to work, but reading them back out errors with:

```
ERROR: permission denied for relation pg_largeobject
```

Perhaps, the Gem needs to use `pg_largeobject_metadata` instead of `pg-largeobject`?

**Comment by krists** [comment]
Yes. It looks like that according to http://www.postgresql.org/docs/current/static/catalog-pg-largeobject.html

**Comment by krists** [comment]
@moubry I saw that you have already forked the repo and made changes. You create a create a merge request and I will merge the changes if all tests pass.

**Comment by moubry** [comment]
I took a stab at fixing the issue by simply replacing `pg_largeobject` with `pg_largeobject_metadata`—which didn't work for me. Since I can't reproduce this issue locally (only on Heroku), I got distracted—I may not be able to finish this pull request. :-/

Refile already has a dependency on ActiveRecord. So maybe a simpler implementation would be using ActiveRecord's interface to [save the files in a binary column](http://ryan.endacott.me/2014/06/10/rails-file-upload.html), which presumably would work independent of database?

**Comment by krists** [comment]
I don't think that binary column approach is a smart idea. By default Rails generates queries like `SELECT * FROM the_thing;`. For example if you would have users table and you would like to store hi-res profile pictures in it. Whenever you would do `User.first.first_name` it would also fetch that image. That is just unnecessary IO and also makes queries slower.

refile-postgres solution stores just the reference to this special large object table.

Regarding this bug. Might be that the postgres user is not a superuser and that could cause this issue. I will investigate this. But `pg_largeobject_metadata` should be used anyway.

**Comment by krists** [comment]
I have released a new version 1.1.3 that uses `pg_largeobject_metadata`. Please check if it solves your Heroku issue.

**Comment by moubry** [comment]
Yeah, I discovered this performance impact very quickly. I ended up having to do:

``` ruby
class User < ActiveRecord::Base
  def upload=(value)
    write_attribute(:upload, value.read) if value.respond_to? :read
  end

  def self.quick_all
    exclude_big_columns = ['upload']
    columns = User.attribute_names - exclude_big_columns
    all.select(columns)
  end
end
```

So to use your example, I have to do `User.quick_all.first.first_name`. Which is not ideal.

I'll try the new version, thank you so much!

**Comment by krists** [comment]
@moubry Have you checked if this works on Heroku?

**Comment by moubry** [comment]
It works! Thank you!
