### ISSUE TITLE
Using oid type in table where oid references are stored.

### ISSUE THREAD

**Issue by kvlou** [krists/refile-postgres#9]
Considering pg_largeobject returns an OID, it will make sense that ID to be stored in the OID type.
Otherwise garbage collection processes like `vacuumlo` cannot count references of orphaned objects.

**Comment by krists** [comment]
Thanks for reporting! Are you planning to sumbit a merge-request with a fix?

**Comment by kvlou** [comment]
Hi Krists, if time permits I will, but that will need to include a migration path from text to OID types. 
I'm part of the Heroku's Department of Data and we had to deal with a client who was using the refile plugin.
